spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USERNAME}
    password: ${DB_TEST_PASSWORD}
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/changelog-master.yml
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
            scope:
              - email

